export const NativeText = typeof Text !== "undefined" ? Text : undefined;
export const NativeImage = typeof Image !== "undefined" ? Image : undefined;

export type * from "./types/index.js"
export * from "./enums.js"
export * from "./main.js"
export * from "./colors/index.js"
export * from "./mockup.js"
export * from "./state.js"
export * from "./props.js"
export * from "./style.js"
export * from "./widgets.js"
export * from "./widget-node.js"
export * from "./collections.js"
export * from "./decorators.js"
export * from "./component.js"
export * from "./kit.js"
export * from "./capability.js"
export * from "./ref.js"
export * from "./view.js"
export * from "./router.js"
export * from "./application.js"
export * from "./composite/index.js"
export * from "./errors/index.js"
export * from "./helpers/index.js"
export * from "./hooks/index.js"
export * from "./capabilities/index.js"
export * from "./layout/index.js"
export * from "./overlay/index.js"
export * from "./engine/index.js"
export * from "./agents/index.js"
